import React, { useRef, useState, useEffect } from "react";
import { View, Text, StyleSheet, ScrollView, TouchableOpacity, Animated, LayoutAnimation, Platform, UIManager } from "react-native";
import { Ionicons } from "@expo/vector-icons";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { useRouter } from "expo-router";

if (Platform.OS === 'android' && UIManager.setLayoutAnimationEnabledExperimental) {
  UIManager.setLayoutAnimationEnabledExperimental(true);
}

const TERMS_SECTIONS = [
  { id: 1, title: "1. Acceptance of Terms", icon: "checkmark-circle", content: "By accessing and using Veytrix, you accept and agree to be bound by the terms and provision of this agreement. In addition, when using these particular services, you shall be subject to any posted guidelines or rules applicable to such services." },
  { id: 2, title: "2. User Responsibilities", icon: "person", content: "You are responsible for maintaining the confidentiality of your account and password and for restricting access to your computer or device. You agree to accept responsibility for all activities that occur under your account or password." },
  { id: 3, title: "3. Acceptable Use", icon: "shield-checkmark", content: "You agree not to use the platform to upload, post, email, or otherwise transmit any material that contains software viruses or any other computer code, files, or programs designed to interrupt, destroy, or limit the functionality of any computer software or hardware or telecommunications equipment." },
  { id: 4, title: "4. Content Ownership", icon: "folder", content: "You retain all of your ownership rights in your content. However, by submitting content to Veytrix, you hereby grant Veytrix a worldwide, non-exclusive, royalty-free, sublicenseable and transferable license to use, reproduce, distribute, prepare derivative works of, display, and perform the content in connection with the service." },
  { id: 5, title: "5. AI Generated Content", icon: "color-wand", content: "Content generated by our AI tools is subject to fair use and intellectual property laws. You are responsible for ensuring that the final output does not infringe on third-party rights." },
  { id: 6, title: "6. Subscriptions", icon: "card", content: "Some parts of the Service are billed on a subscription basis. You will be billed in advance on a recurring and periodic basis (such as daily, weekly, monthly or annually), depending on the type of subscription plan you select when purchasing the Subscription." },
  { id: 7, title: "7. Credits", icon: "sparkles", content: "AI features require credits. Credits are non-transferable and may expire if your account remains inactive for a period of 12 months." },
  { id: 8, title: "8. Payments", icon: "cash", content: "All payments are processed securely through our third-party payment providers. We do not store your full credit card information." },
  { id: 9, title: "9. Refund Policy", icon: "refresh", content: "Refunds for subscriptions or credits are handled on a case-by-case basis. Generally, if you cancel within 14 days of your initial purchase and have not used any credits, you are eligible for a full refund." },
  { id: 10, title: "10. Account Suspension", icon: "lock-closed", content: "We may terminate or suspend access to our Service immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms." },
  { id: 11, title: "11. Privacy", icon: "eye-off", content: "Your use of Veytrix is also governed by our Privacy Policy. Please review our Privacy Policy to understand our practices." },
  { id: 12, title: "12. Updates", icon: "cloud-download", content: "We reserve the right, at our sole discretion, to modify or replace these Terms at any time. If a revision is material we will try to provide at least 30 days' notice prior to any new terms taking effect." },
  { id: 13, title: "13. Limitation of Liability", icon: "warning", content: "In no event shall Veytrix, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the Service." },
  { id: 14, title: "14. Termination", icon: "close-circle", content: "Upon termination, your right to use the Service will immediately cease. If you wish to terminate your account, you may simply discontinue using the Service." },
  { id: 15, title: "15. Contact", icon: "mail", content: "If you have any questions about these Terms, please contact us at legal@veytrix.com." },
];

export function TermsScreen() {
  const insets = useSafeAreaInsets();
  const router = useRouter();
  const [expandedId, setExpandedId] = useState<number | null>(null);
  
  const fadeAnim = useRef(new Animated.Value(0)).current;
  
  useEffect(() => {
    Animated.timing(fadeAnim, {
      toValue: 1,
      duration: 400,
      useNativeDriver: true,
    }).start();
  }, [fadeAnim]);

  const toggleExpand = (id: number) => {
    LayoutAnimation.configureNext(LayoutAnimation.Presets.easeInEaseOut);
    setExpandedId(expandedId === id ? null : id);
  };

  return (
    <Animated.View style={[styles.container, { opacity: fadeAnim }]}>
      <View style={[styles.header, { paddingTop: insets.top + 16 }]}>
        <TouchableOpacity style={styles.backBtn} onPress={() => router.back()}>
          <Ionicons name="arrow-back" size={24} color="#1D2B64" />
        </TouchableOpacity>
        <View style={styles.headerTitleContainer}>
          <Text style={styles.title}>Terms & Conditions</Text>
          <Text style={styles.subtitle}>Please read before using Veytrix.</Text>
        </View>
      </View>

      <ScrollView contentContainerStyle={[styles.scrollContent, { paddingBottom: insets.bottom + 40 }]} showsVerticalScrollIndicator={false}>
        
        {TERMS_SECTIONS.map((section) => {
          const isExpanded = expandedId === section.id;
          return (
            <TouchableOpacity 
              key={section.id} 
              style={[styles.card, isExpanded && styles.cardExpanded]}
              activeOpacity={0.8}
              onPress={() => toggleExpand(section.id)}
            >
              <View style={styles.cardHeader}>
                <View style={[styles.iconWrap, { backgroundColor: isExpanded ? "#3B6CE7" : "#F5F7FA" }]}>
                  <Ionicons name={section.icon as any} size={20} color={isExpanded ? "#fff" : "#1D2B64"} />
                </View>
                <Text style={styles.cardTitle}>{section.title}</Text>
                <Ionicons name={isExpanded ? "chevron-up" : "chevron-down"} size={20} color="#8E8E93" />
              </View>
              {isExpanded && (
                <View style={styles.cardBody}>
                  <Text style={styles.paragraph}>{section.content}</Text>
                </View>
              )}
            </TouchableOpacity>
          );
        })}

        <View style={[styles.card, styles.bottomCard]}>
          <View style={styles.metaRow}>
            <Text style={styles.metaLabel}>Last Updated</Text>
            <Text style={styles.metaValue}>July 21, 2026</Text>
          </View>
          <View style={styles.metaDivider} />
          <View style={styles.metaRow}>
            <Text style={styles.metaLabel}>Effective Date</Text>
            <Text style={styles.metaValue}>August 1, 2026</Text>
          </View>
          
          <TouchableOpacity style={styles.agreeBtn} disabled>
            <Ionicons name="checkmark-circle" size={20} color="#3B6CE7" style={{ marginRight: 8 }} />
            <Text style={styles.agreeBtnText}>Terms Accepted</Text>
          </TouchableOpacity>
        </View>
        
      </ScrollView>
    </Animated.View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#F5F7FA" },
  header: { paddingHorizontal: 20, paddingBottom: 16, backgroundColor: "#fff", shadowColor: "#000", shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.05, shadowRadius: 4, elevation: 3, zIndex: 10, flexDirection: "row", alignItems: "center" },
  backBtn: { width: 44, height: 44, borderRadius: 22, backgroundColor: "#F5F7FA", justifyContent: "center", alignItems: "center", marginRight: 16 },
  headerTitleContainer: { flex: 1 },
  title: { fontSize: 24, fontWeight: "800", color: "#1D2B64", marginBottom: 2 },
  subtitle: { fontSize: 13, color: "#8E8E93", fontWeight: "500" },
  scrollContent: { padding: 20, gap: 12 },
  card: { backgroundColor: "#fff", borderRadius: 20, padding: 16, shadowColor: "#1D2B64", shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.04, shadowRadius: 12, elevation: 2 },
  cardExpanded: { shadowOpacity: 0.08, shadowRadius: 16, elevation: 4 },
  cardHeader: { flexDirection: "row", alignItems: "center" },
  iconWrap: { width: 40, height: 40, borderRadius: 12, justifyContent: "center", alignItems: "center", marginRight: 12 },
  cardTitle: { flex: 1, fontSize: 16, fontWeight: "700", color: "#1D2B64" },
  cardBody: { marginTop: 16, paddingTop: 16, borderTopWidth: 1, borderTopColor: "#F5F7FA" },
  paragraph: { fontSize: 15, color: "#5F7695", lineHeight: 24 },
  bottomCard: { marginTop: 12, backgroundColor: "#fff" },
  metaRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", paddingVertical: 8 },
  metaLabel: { fontSize: 14, color: "#8E8E93", fontWeight: "500" },
  metaValue: { fontSize: 14, color: "#1D2B64", fontWeight: "700" },
  metaDivider: { height: 1, backgroundColor: "#F5F7FA", marginVertical: 8 },
  agreeBtn: { flexDirection: "row", backgroundColor: "rgba(59, 108, 231, 0.1)", marginTop: 20, paddingVertical: 14, borderRadius: 16, justifyContent: "center", alignItems: "center" },
  agreeBtnText: { color: "#3B6CE7", fontSize: 15, fontWeight: "700" },
});
